version: "3.9"

services:
  app:
    build:
      dockerfile: ./Dockerfile
    env_file:
      - .env
    networks:
      local:

  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-sosiska_db}
      POSTGRES_USER: ${POSTGRES_USER:-sosiska}
      POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD:-sosiska}
    ports:
      - "5432:5432"
    volumes:
      - ./data/:/var/lib/postgresql/data
    networks:
      local:

networks:
  local:
    name: local
    external: true
